### ISSUE TITLE
latest apk needs mod

### ISSUE THREAD

**Issue by sbranden** [wtengi/redsquaretvapp#1]

**Comment by wtengi** [comment]
updated,  new location of the parameter in classes 4, file moded, and uploaded. You can repack it with the classes4.dex in resources

**Comment by sbranden** [comment]
I repacked and it has the same behavior as original apk.  Closes after clicking getting started button.

**Comment by wtengi** [comment]
not to sure why, it doesn't work for you, did it and repack in 5 min, and works no problem.. give me your email I'll just send you a copy

**Comment by sbranden** [comment]
Thanks - I am using google chromecast with google tv.  
sb319958@gmail.com
